### ISSUE TITLE
How to get the final tranformation between source and target cloud ?

### ISSUE THREAD

**Issue by Bannigo** [palanglois/icpSparse#2]
Hello,
         I have recently come to the attention of Sparse ICP. I have a question on how to get the final transformation matrix between source and target cloud?

**Comment by palanglois** [comment]
Hello,

Thanks for your interest!
The output matrix is given in the console output. 

For instance if I run 

    ./icpSparse -i1 ../media/bunny_side1.obj -i2 ../media/bunny_side2.obj -pl -o .

I get 

    Computed Rotation : 
    0.821356 0.0622843 -0.567005
    -0.29407   0.89798 -0.327344
    0.488771  0.435605  0.755878
    Computed Translation : 
    -0.0411258
    -0.0246447
    -0.0190352

I hope this helps !

**Comment by Bannigo** [comment]
Hello,
Thank you so much for your quick reply. This helps!!!
